#!/usr/bin/env bash
#transfers a file from a client to a server

if [ "$#" -lt 3 ];
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi

file_path=$1
ip_addr=$2
user=$3
ssh_key=$4

scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$user@$ip_addr":~/
