#!/usr/bin/env bash
#a Bash script that redirects to another page

apt-get update

apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

echo "<html><head><meta http-equiv='refresh' content='0;url=/new-page'></head></html>" > /var/www/html/redirect_me/index.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	server_name 315196-web-01;

	location / {
		try_files \$uri \$uri/ =404;
	}

	location /redirect_me {
        return 301 /new-page;
	}
	
	location = /index.html {
        try_files \$uri =404;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
