#!/usr/bin/env bash
#a Bash script that configures a new Ubuntu machine

apt-get update

apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

echo "Ceci n'est pas une page." > /var/www/html/404.html

echo "server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html;

	server_name 315196-web-01;

	location / {
		try_files \$uri \$uri/ =404;
	}

	error_page 404 /404.html;
	location = /404.html {
	root /var/www/html;
	internal;
	}

	location = /index.html {
        try_files \$uri =404;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
