#!/usr/bin/env bash
#script that Configures Nginx so that its HTTP response contains a custom header

sudo apt-get update

sudo apt-get install -y nginx

custom_header_config="add_header X-Served-By \$hostname;"

sudo sh -c "echo \"$custom_header_config\" > /etc/nginx/conf.d/custom_header"

sudo service nginx restart
