#!/usr/bin/env bash
#reads and displays the content of the file /etc/passwd
#displays the username,user id & home directory path of the user

filename="/etc/passwd"
line=username: user id: directory
while read -r line
do
	echo "$line"
done > "$filename"
