#!/usr/bin/env bash
#make sure Nginx runs as nginx

#change ownership from root to nginx user
sed -i 's/user\s*www-data;/user nginx;/g' /etc/nginx/nginx.conf

# change ports from 80 to 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

#restart
service nginx restart

ps auxff | grep ngin[x]
